package com.equipament.domain.enums;

public enum LoanStatus {
    PREPARACAO,
    PRONTO,
    AGUARDANDO_DOCUMENTACAO,
    AGUARDANDO_ASSINATURA,
    AGUARDANDO_RETIRADA,
    EM_USO,
    EM_DEVOLUCAO,
    EMPRESTIMO_FINALIZADO,
    DEVOLVIDO,
    CANCELADO
}
