spring.application.name=inventory

spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=reconcavo_inventory;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=230856
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu-email@gmail.com
spring.mail.password=sua-senha-de-aplicativo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs

springdoc.swagger-ui.operations-sorter=alpha
springdoc.show-login-endpoint=true

springdoc.swagger-ui.validator-url=none

server.error.include-message=always

# Permite que cada imagem individual tenha até 5MB
spring.servlet.multipart.max-file-size=5MB

# Permite que o conjunto total de imagens enviadas de uma vez tenha até 50MB
spring.servlet.multipart.max-request-size=50MB

# Caminho onde as fotos serão salvas fisicamente no servidor
app.upload.dir=C:/uploads/